name: Update legislation
on:
  - push
  - workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Review checkout
        run: |
          git lfs ls-files -s
      - name: Install Python dependencies
        run: |
          python3 -m pip install nbconvert papermill
          python3 -m pip install -r requirements.txt
      - name: Run notebooks
        run: |
          cd notebooks
          jupyter nbconvert --to notebook --inplace --execute Committees.ipynb
          jupyter nbconvert --to notebook --inplace --execute LegislativeMembers.ipynb
          python3 update_legislation.py
      - name: Review output
        run: |
          git lfs ls-files -s
          git status
      - uses: stefanzweifel/git-auto-commit-action@v4
